# Format is <key name>: <value> (with a space after the : )
# E.g.
# update_level: patch
  
# aseprite_path: <REPLACE ME, and remove # from beginning of this line>
    # Point this to your Aseprite.exe absolute path, for example: 
    # aseprite_path: C:/Program Files/Aseprite/aseprite.exe
    # This is needed for the assistant to automatically export your animations to spritesheets.
    # If you use Steam for Aseprite, you can find the path with:
    #   The aseprite page of your library, The gear icon at the top right,
    #   Manage, Browse Local Files, Copy the path of Aseprite.exe to the config.
    
    
    # Aseprite Tag Color Configs
    # Legal values are:
    #   black, red, orange, yellow, green, blue, purple, gray
anim_tag_color: blue
    # The color of Aseprite tag representing an animation. 
    # If you keep multiple aseprite animations in a file, put each in a tag with this 
    # color, and the assistant will export them under that tag's name.
window_tag_color: red
    # The color of Aseprite tag representing an attack window.
    # If a tag of this color is found, it will be used to add animation meta-data to the 
    # bottom of the attack's script.

library_update_level: patch
    # What kind of library updates to allow. 
    # This only affects the functions available to inject, not assistant behavior.
    # major = All updates are allowed, even if they may 
    #   break existing code.
    # minor = Don't allow breaking changes to existing 
    #   functions, but do allow new functions. Could cause name collisions.
    # patch = Only allow changes to existing functions 
    #   that fix bugs or can't break current functionality.
    # none = No updates.
    
assistant_should_self_update: False
    # If the assistant should automatically receive behavior updates.
